import { UserRole } from "@prisma/client";

type AdminAudience = "auditor" | "manager" | "super_admin";

export type AdminNavItem = {
  id: string;
  href: string;
  label: string;
  description?: string;
  aliases?: string[];
  audiences: AdminAudience[];
  sidebar?: boolean;
  /** Collapsible section label in the left rail (mobile-first grouping). */
  sidebarGroup?: string;
  palette?: boolean;
  dashboardCard?: boolean;
  quickActionLabel?: string;
};

const ADMIN_NAV_ITEMS: AdminNavItem[] = [
  {
    id: "dashboard",
    href: "/admin/",
    label: "Dashboard",
    aliases: ["home"],
    audiences: ["auditor", "manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Overview",
    palette: true,
  },
  {
    id: "site-content",
    href: "/admin/site-content",
    label: "Site content",
    description: "Manage public dates, venue lines, and event copy.",
    aliases: ["content"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Overview",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Update public event copy",
  },
  {
    id: "contact-inquiries",
    href: "/admin/contact-inquiries",
    label: "Contact inquiries",
    description: "Review messages submitted from the public contact form.",
    aliases: ["contact", "inquiries", "messages"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Overview",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Review contact inbox",
  },
  {
    id: "programs",
    href: "/admin/programs",
    label: "Programs & Categories",
    description: "Set up programs, timelines, and award categories.",
    aliases: ["programs"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Programs & entries",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Configure programs",
  },
  {
    id: "entries",
    href: "/admin/entries",
    label: "Review Entries & Assign Judges",
    description: "Assign judges and update entry progress.",
    aliases: ["submissions"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Programs & entries",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Assign judges now",
  },
  {
    id: "nominations",
    href: "/admin/nominations",
    label: "Review Nominations",
    description: "Review nominations, approve decisions, and convert them to entries.",
    aliases: ["nomination", "awardee", "convert"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Programs & entries",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Review nominations",
  },
  {
    id: "events",
    href: "/admin/events",
    label: "Event Management",
    description: "Manage registration, ticketing, and guest check-in.",
    aliases: ["attendance", "registrations"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Events & onsite",
    palette: true,
    dashboardCard: true,
  },
  {
    id: "event-checkin",
    href: "/admin/events/checkin",
    label: "Guest Check-In",
    description: "Check in guests quickly with scanner support.",
    aliases: ["scanner", "onsite", "desk", "checkin"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Events & onsite",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Open guest check-in",
  },
  {
    id: "event-badge",
    href: "/admin/events/badge",
    label: "Badge Printing",
    description: "Print attendee badges and keep print history.",
    aliases: ["badge", "print", "name tag"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Events & onsite",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Open badge printing",
  },
  {
    id: "event-onsite",
    href: "/admin/events/onsite",
    label: "Event Reports",
    description: "View attendance, check-in activity, and print summaries.",
    aliases: ["throughput", "gates", "checkin report"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Events & onsite",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Open event reports",
  },
  {
    id: "leaderboard",
    href: "/admin/leaderboard",
    label: "Judge Dashboard",
    description: "View judge scores and ranking trends.",
    aliases: ["scores"],
    audiences: ["auditor", "manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Judging & voting",
    palette: true,
    dashboardCard: true,
  },
  {
    id: "voting",
    href: "/admin/voting",
    label: "Voting Results",
    description: "View vote rankings by entry and category.",
    aliases: ["votes"],
    audiences: ["auditor", "manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Judging & voting",
    palette: true,
    dashboardCard: true,
  },
  {
    id: "voting-fraud",
    href: "/admin/voting-fraud",
    label: "Voting Reports",
    description: "Review unusual voting activity and alerts.",
    aliases: ["risk"],
    audiences: ["auditor", "manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Judging & voting",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Open voting reports",
  },
  {
    id: "voting-quarantine",
    href: "/admin/voting-quarantine",
    label: "Votes to Review",
    description: "Review flagged votes and decide whether to approve or reject.",
    aliases: ["queue", "quarantine"],
    audiences: ["auditor", "manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Judging & voting",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Review flagged votes",
  },
  {
    id: "certificates",
    href: "/admin/certificates",
    label: "Certificates",
    description: "Generate and manage recognition certificates.",
    aliases: ["certs"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Administration",
    palette: true,
    dashboardCard: true,
  },
  {
    id: "advanced",
    href: "/admin/advanced",
    label: "Admin Tools",
    description: "Manage judging setup and send announcements.",
    aliases: ["tools"],
    audiences: ["manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Administration",
    palette: true,
    dashboardCard: true,
  },
  {
    id: "exports",
    href: "/admin/exports",
    label: "Data Downloads",
    description: "Download reports as CSV or ZIP files.",
    aliases: ["csv", "zip"],
    audiences: ["auditor", "manager", "super_admin"],
    sidebar: true,
    sidebarGroup: "Administration",
    palette: true,
    dashboardCard: true,
    quickActionLabel: "Download reports",
  },
  {
    id: "users",
    href: "/admin/users",
    label: "Team Accounts",
    description: "Create and manage team access levels.",
    aliases: ["staff", "users"],
    audiences: ["super_admin"],
    sidebar: true,
    sidebarGroup: "Administration",
    palette: true,
    dashboardCard: true,
  },
  {
    id: "entrant-portal",
    href: "/portal/entrant",
    label: "Entrant Dashboard",
    description: "Open the entrant dashboard and submissions area.",
    aliases: ["entrant"],
    audiences: ["manager", "super_admin"],
    palette: true,
    dashboardCard: true,
  },
  {
    id: "nominator-portal",
    href: "/portal/nominator",
    label: "Nominator Dashboard",
    description: "Open the nominator dashboard and nominations area.",
    aliases: ["nominator", "nominate", "awardee"],
    audiences: ["manager", "super_admin"],
    palette: true,
    dashboardCard: true,
  },
  {
    id: "judge-portal",
    href: "/portal/judge",
    label: "Judge Dashboard",
    description: "Open the judge dashboard for scoring and reviews.",
    aliases: ["judge"],
    audiences: ["manager", "super_admin"],
    palette: true,
    dashboardCard: true,
  },
  {
    id: "public-vote",
    href: "/vote",
    label: "Public voting page",
    description: "Open the public-facing voting experience.",
    audiences: ["auditor", "manager", "super_admin"],
    dashboardCard: true,
  },
];

function roleAudience(role: UserRole): AdminAudience {
  if (role === UserRole.AUDITOR) return "auditor";
  if (role === UserRole.SUPER_ADMIN) return "super_admin";
  return "manager";
}

export function getAdminNavItems(role: UserRole): AdminNavItem[] {
  const audience = roleAudience(role);
  return ADMIN_NAV_ITEMS.filter((item) => item.audiences.includes(audience));
}
